from . import odoogpt_settings_mixin
from . import res_company
from . import res_config_settings
from . import res_users
from . import mail_channel
from . import odoogpt_openai_utils
from . import odoogpt_openai_mixin
from . import odoogpt_openai_log
from . import odoogpt_openai_model
from . import odoogpt_openai_file
from . import odoogpt_openai_fine_tune